### PR TITLE
Release IPAM's IP when error occurs

### LINKED ISSUE #39: Release IP from IPAM if cmdAdd failed
After gain IPAM's ip in CMD ADD release it if error happens

this code can help solving the issue in cmdAdd

After:
`if result.IP4 == nil {
		return errors.New("IPAM plugin returned missing IPv4 config")
	}`

add: 

`
defer func() {
		if err != nil {
			ipam.ExecDel(n.IPAM.Type, args.StdinData)
		}
	}()
`

### PR DESCRIPTION
**Pull request by Mmduh-483**
After gain IPAM's ip in CMD ADD release it if error happens

Fixes #39

### CODE REVIEW

File: sriov/main.go [hunk 1]
```diff
@@ -79,6 +79,12 @@ func cmdAdd(args *skel.CmdArgs) error {
 		return errors.New("IPAM plugin returned missing IPv4 config")
 	}
 
+	defer func() {
+		if err != nil {
+			ipam.ExecDel(n.IPAM.Type, args.StdinData)
+		}
+	}()
+
 	err = netns.Do(func(_ ns.NetNS) error {
```
Comment (ahalim-intel) [inline sriov/main.go]: This will disregard error on L:89 which is IMO what we want to check most.
After getting an IP on L:73 we might fail on configuring the interface on L:89 and only then we should try to release the IP that was allocated. So, this defer block should be moved after L:90 here.

Comment (moshe010) [reply sriov/main.go]: if we failed on the move namespace we need to call ipam.ExecDel to return the ip address to the pool. 
you can see a good example with macvlan see [1]. 

[1] - https://github.com/containernetworking/plugins/blob/master/plugins/main/macvlan/macvlan.go#L173-L184

Comment (ahalim-intel) [reply sriov/main.go]: I got that. My concern was if this defer block would get the errors coming from further down. I just double checked it again, see no issues.
